
project_id = "npvfusgiqvswmviohhqc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.generate-predictions]
verify_jwt = false

[functions.ingest-schedule]
verify_jwt = false

[functions.fetch-schedule]
verify_jwt = false

[functions.monte-carlo-simulation]
verify_jwt = false

[functions.ingest-lineups]
verify_jwt = false

[functions.lineup-scheduler]
verify_jwt = false

[functions.lineup-orchestrator]
verify_jwt = false

[functions.lineup-monitor]
verify_jwt = false
